Output demo.gif
Set FontSize 18
Set Width 1920
Set Height 1080
Set Shell zsh
Sleep 2s
Type "cargo run dev"
Enter
Sleep 1s
Enter
Sleep 500ms
Type "wdwwww"
Sleep 500ms
Type "s"
Sleep 500ms
Type "s"
Enter
Sleep 1s
Escape
Sleep 500ms
Type "wwwwww"
Sleep 500ms
Type "d"
Sleep 1s
Type "qss"
Sleep 500ms
Type "www"
Sleep 1s
Escape
Sleep 500ms
Escape
Sleep 500ms
Escape
Type "[C"
Enter
Escape
Sleep 1.5s
Enter
Sleep 6s

